-- =============================================================================
-- SMS Associates — initial database schema (Phase 2)
--
--   1. Extensions (the trigram search indexes need pg_trgm)
--   2. Tables, enums, indexes and foreign keys generated by Prisma from
--      prisma/schema.prisma
--   3. Rules Prisma's schema language cannot express: CHECK constraints, the
--      stock-ledger trigger, history guards and read-only views
--      (validated in the design, docs/DATABASE.md §8 and §11)
--
-- Applied migrations are never edited; changes go in a new migration.
-- =============================================================================

-- ─── 0. Extensions ──────────────────────────────────────────────────────────

CREATE EXTENSION IF NOT EXISTS pg_trgm;

-- ─── Prisma-generated schema ────────────────────────────────────────────────

-- CreateSchema
CREATE SCHEMA IF NOT EXISTS "public";

-- CreateEnum
CREATE TYPE "rental_status" AS ENUM ('DRAFT', 'ACTIVE', 'PARTIALLY_RETURNED', 'RETURNED', 'CANCELLED');

-- CreateEnum
CREATE TYPE "settlement_status" AS ENUM ('NO_DUE', 'PAYMENT_PENDING', 'ADDITIONAL_DUE', 'REFUND_DUE', 'SETTLED');

-- CreateEnum
CREATE TYPE "day_count_rule" AS ENUM ('CALENDAR_DAYS_MIN_1');

-- CreateEnum
CREATE TYPE "return_condition" AS ENUM ('GOOD', 'DAMAGED', 'LOST');

-- CreateEnum
CREATE TYPE "payment_type" AS ENUM ('ADVANCE', 'ADDITIONAL', 'REFUND', 'DISCOUNT');

-- CreateEnum
CREATE TYPE "payment_method" AS ENUM ('CASH', 'UPI');

-- CreateEnum
CREATE TYPE "payment_status" AS ENUM ('PENDING', 'COMPLETED', 'CANCELLED');

-- CreateEnum
CREATE TYPE "charge_type" AS ENUM ('DAMAGE', 'LOSS', 'OTHER');

-- CreateEnum
CREATE TYPE "document_type" AS ENUM ('PHOTO', 'ID_PROOF', 'OTHER');

-- CreateEnum
CREATE TYPE "inventory_transaction_type" AS ENUM ('INITIAL_STOCK', 'MANUAL_ADJUSTMENT', 'RENTAL_OUT', 'RETURN_IN', 'RETURN_TO_HOLD', 'HOLD_RELEASE', 'HOLD_WRITE_OFF', 'BILL_VOID_REVERSAL', 'RETURN_VOID_REVERSAL');

-- CreateTable
CREATE TABLE "users" (
    "id" TEXT NOT NULL,
    "name" TEXT NOT NULL,
    "email" TEXT NOT NULL,
    "email_verified" BOOLEAN NOT NULL DEFAULT false,
    "image" TEXT,
    "username" TEXT,
    "display_username" TEXT,
    "role" TEXT NOT NULL DEFAULT 'staff',
    "banned" BOOLEAN NOT NULL DEFAULT false,
    "ban_reason" TEXT,
    "ban_expires" TIMESTAMPTZ(3),
    "created_at" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMPTZ(3) NOT NULL,

    CONSTRAINT "users_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "sessions" (
    "id" TEXT NOT NULL,
    "token" TEXT NOT NULL,
    "user_id" TEXT NOT NULL,
    "expires_at" TIMESTAMPTZ(3) NOT NULL,
    "ip_address" TEXT,
    "user_agent" TEXT,
    "impersonated_by" TEXT,
    "created_at" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMPTZ(3) NOT NULL,

    CONSTRAINT "sessions_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "accounts" (
    "id" TEXT NOT NULL,
    "account_id" TEXT NOT NULL,
    "provider_id" TEXT NOT NULL,
    "user_id" TEXT NOT NULL,
    "password" TEXT,
    "access_token" TEXT,
    "refresh_token" TEXT,
    "id_token" TEXT,
    "access_token_expires_at" TIMESTAMPTZ(3),
    "refresh_token_expires_at" TIMESTAMPTZ(3),
    "scope" TEXT,
    "created_at" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMPTZ(3) NOT NULL,

    CONSTRAINT "accounts_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "verifications" (
    "id" TEXT NOT NULL,
    "identifier" TEXT NOT NULL,
    "value" TEXT NOT NULL,
    "expires_at" TIMESTAMPTZ(3) NOT NULL,
    "created_at" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMPTZ(3) NOT NULL,

    CONSTRAINT "verifications_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "business_profiles" (
    "id" UUID NOT NULL,
    "version" INTEGER NOT NULL,
    "name" TEXT NOT NULL,
    "tagline" TEXT NOT NULL,
    "address_lines" TEXT[],
    "phones" TEXT[],
    "bill_title" TEXT NOT NULL DEFAULT 'Rental Bill',
    "logo_key" TEXT,
    "created_by_id" TEXT,
    "created_at" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "business_profiles_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "counters" (
    "key" TEXT NOT NULL,
    "value" INTEGER NOT NULL DEFAULT 0,
    "updated_at" TIMESTAMPTZ(3) NOT NULL,

    CONSTRAINT "counters_pkey" PRIMARY KEY ("key")
);

-- CreateTable
CREATE TABLE "customers" (
    "id" UUID NOT NULL,
    "name" TEXT NOT NULL,
    "phone" TEXT NOT NULL,
    "location" TEXT NOT NULL,
    "occupation" TEXT,
    "created_by_id" TEXT NOT NULL,
    "archived_at" TIMESTAMPTZ(3),
    "archived_by_id" TEXT,
    "archive_reason" TEXT,
    "created_at" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMPTZ(3) NOT NULL,

    CONSTRAINT "customers_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "customer_documents" (
    "id" UUID NOT NULL,
    "customer_id" UUID NOT NULL,
    "type" "document_type" NOT NULL,
    "label" TEXT,
    "is_sensitive" BOOLEAN NOT NULL,
    "storage_key" TEXT NOT NULL,
    "file_name" TEXT NOT NULL,
    "mime_type" TEXT NOT NULL,
    "size_bytes" INTEGER NOT NULL,
    "sha256" TEXT NOT NULL,
    "uploaded_by_id" TEXT NOT NULL,
    "created_at" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "customer_documents_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "materials" (
    "id" UUID NOT NULL,
    "name" TEXT NOT NULL,
    "description" TEXT,
    "sort_order" INTEGER NOT NULL DEFAULT 0,
    "is_active" BOOLEAN NOT NULL DEFAULT true,
    "created_at" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMPTZ(3) NOT NULL,

    CONSTRAINT "materials_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "material_variants" (
    "id" UUID NOT NULL,
    "material_id" UUID NOT NULL,
    "variant_name" TEXT NOT NULL DEFAULT '',
    "rate_per_day" DECIMAL(10,2),
    "low_stock_threshold" INTEGER,
    "sort_order" INTEGER NOT NULL DEFAULT 0,
    "is_active" BOOLEAN NOT NULL DEFAULT true,
    "created_at" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMPTZ(3) NOT NULL,

    CONSTRAINT "material_variants_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "inventory" (
    "variant_id" UUID NOT NULL,
    "total_quantity" INTEGER NOT NULL DEFAULT 0,
    "rented_quantity" INTEGER NOT NULL DEFAULT 0,
    "held_quantity" INTEGER NOT NULL DEFAULT 0,
    "updated_at" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "inventory_pkey" PRIMARY KEY ("variant_id")
);

-- CreateTable
CREATE TABLE "inventory_transactions" (
    "id" UUID NOT NULL,
    "variant_id" UUID NOT NULL,
    "type" "inventory_transaction_type" NOT NULL,
    "total_delta" INTEGER NOT NULL DEFAULT 0,
    "rented_delta" INTEGER NOT NULL DEFAULT 0,
    "held_delta" INTEGER NOT NULL DEFAULT 0,
    "occurred_at" TIMESTAMPTZ(3) NOT NULL,
    "bill_id" UUID,
    "bill_item_id" UUID,
    "return_id" UUID,
    "return_item_id" UUID,
    "customer_id" UUID,
    "reason" TEXT,
    "created_by_id" TEXT NOT NULL,
    "created_at" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "inventory_transactions_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "bills" (
    "id" UUID NOT NULL,
    "bill_seq" INTEGER NOT NULL,
    "bill_number" TEXT NOT NULL,
    "status" "rental_status" NOT NULL DEFAULT 'DRAFT',
    "settlement_status" "settlement_status" NOT NULL DEFAULT 'NO_DUE',
    "customer_id" UUID NOT NULL,
    "taken_at" TIMESTAMPTZ(3) NOT NULL,
    "expected_days" INTEGER NOT NULL,
    "expected_return_date" DATE NOT NULL,
    "site_location" TEXT NOT NULL,
    "notes" TEXT,
    "paper_bill_number" TEXT,
    "customer_name" TEXT NOT NULL,
    "customer_phone" TEXT NOT NULL,
    "customer_location" TEXT NOT NULL,
    "business_profile_id" UUID NOT NULL,
    "day_count_rule" "day_count_rule" NOT NULL DEFAULT 'CALENDAR_DAYS_MIN_1',
    "time_zone" TEXT NOT NULL DEFAULT 'Asia/Kolkata',
    "estimated_amount" DECIMAL(12,2) NOT NULL DEFAULT 0,
    "draft_advance_amount" DECIMAL(12,2),
    "draft_advance_method" "payment_method",
    "draft_advance_received" BOOLEAN,
    "draft_advance_reference" TEXT,
    "version" INTEGER NOT NULL DEFAULT 1,
    "created_by_id" TEXT NOT NULL,
    "generated_at" TIMESTAMPTZ(3),
    "generated_by_id" TEXT,
    "cancelled_at" TIMESTAMPTZ(3),
    "cancelled_by_id" TEXT,
    "cancel_reason" TEXT,
    "archived_at" TIMESTAMPTZ(3),
    "archived_by_id" TEXT,
    "archive_reason" TEXT,
    "created_at" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMPTZ(3) NOT NULL,

    CONSTRAINT "bills_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "bill_items" (
    "id" UUID NOT NULL,
    "bill_id" UUID NOT NULL,
    "line_no" INTEGER NOT NULL,
    "variant_id" UUID NOT NULL,
    "material_name" TEXT NOT NULL,
    "variant_name" TEXT NOT NULL,
    "quantity" INTEGER NOT NULL,
    "rate_per_day" DECIMAL(10,2) NOT NULL,
    "estimated_amount" DECIMAL(12,2) NOT NULL,
    "returned_quantity" INTEGER NOT NULL DEFAULT 0,
    "damaged_quantity" INTEGER NOT NULL DEFAULT 0,
    "lost_quantity" INTEGER NOT NULL DEFAULT 0,

    CONSTRAINT "bill_items_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "returns" (
    "id" UUID NOT NULL,
    "bill_id" UUID NOT NULL,
    "return_no" INTEGER NOT NULL,
    "returned_at" TIMESTAMPTZ(3) NOT NULL,
    "notes" TEXT,
    "idempotency_key" UUID NOT NULL,
    "processed_by_id" TEXT NOT NULL,
    "voided_at" TIMESTAMPTZ(3),
    "voided_by_id" TEXT,
    "void_reason" TEXT,
    "created_at" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "returns_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "return_items" (
    "id" UUID NOT NULL,
    "return_id" UUID NOT NULL,
    "bill_item_id" UUID NOT NULL,
    "condition" "return_condition" NOT NULL,
    "quantity" INTEGER NOT NULL,
    "chargeable_days" INTEGER NOT NULL,
    "rate_per_day" DECIMAL(10,2) NOT NULL,
    "amount" DECIMAL(12,2) NOT NULL,
    "note" TEXT,

    CONSTRAINT "return_items_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "payments" (
    "id" UUID NOT NULL,
    "bill_id" UUID NOT NULL,
    "type" "payment_type" NOT NULL,
    "status" "payment_status" NOT NULL,
    "amount" DECIMAL(12,2) NOT NULL,
    "method" "payment_method",
    "transaction_reference" TEXT,
    "note" TEXT,
    "received_at" TIMESTAMPTZ(3),
    "return_id" UUID,
    "idempotency_key" UUID NOT NULL,
    "recorded_by_id" TEXT NOT NULL,
    "status_changed_at" TIMESTAMPTZ(3),
    "status_changed_by_id" TEXT,
    "status_change_reason" TEXT,
    "created_at" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "payments_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "bill_charges" (
    "id" UUID NOT NULL,
    "bill_id" UUID NOT NULL,
    "type" "charge_type" NOT NULL,
    "amount" DECIMAL(12,2) NOT NULL,
    "description" TEXT NOT NULL,
    "return_item_id" UUID,
    "created_by_id" TEXT NOT NULL,
    "voided_at" TIMESTAMPTZ(3),
    "voided_by_id" TEXT,
    "void_reason" TEXT,
    "created_at" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "bill_charges_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "audit_logs" (
    "id" UUID NOT NULL,
    "actor_id" TEXT,
    "action" TEXT NOT NULL,
    "entity_type" TEXT NOT NULL,
    "entity_id" TEXT NOT NULL,
    "summary" TEXT NOT NULL,
    "changes" JSONB,
    "ip_address" TEXT,
    "user_agent" TEXT,
    "created_at" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "audit_logs_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE UNIQUE INDEX "users_email_key" ON "users"("email");

-- CreateIndex
CREATE UNIQUE INDEX "users_username_key" ON "users"("username");

-- CreateIndex
CREATE UNIQUE INDEX "sessions_token_key" ON "sessions"("token");

-- CreateIndex
CREATE INDEX "sessions_user_id_idx" ON "sessions"("user_id");

-- CreateIndex
CREATE INDEX "accounts_user_id_idx" ON "accounts"("user_id");

-- CreateIndex
CREATE INDEX "verifications_identifier_idx" ON "verifications"("identifier");

-- CreateIndex
CREATE UNIQUE INDEX "business_profiles_version_key" ON "business_profiles"("version");

-- CreateIndex
CREATE INDEX "customers_phone_idx" ON "customers"("phone");

-- CreateIndex
CREATE INDEX "customers_name_trgm_idx" ON "customers" USING GIN ("name" gin_trgm_ops);

-- CreateIndex
CREATE INDEX "customers_location_trgm_idx" ON "customers" USING GIN ("location" gin_trgm_ops);

-- CreateIndex
CREATE INDEX "customers_created_at_idx" ON "customers"("created_at");

-- CreateIndex
CREATE UNIQUE INDEX "customer_documents_storage_key_key" ON "customer_documents"("storage_key");

-- CreateIndex
CREATE INDEX "customer_documents_customer_id_created_at_idx" ON "customer_documents"("customer_id", "created_at");

-- CreateIndex
CREATE UNIQUE INDEX "materials_name_key" ON "materials"("name");

-- CreateIndex
CREATE INDEX "material_variants_material_id_sort_order_idx" ON "material_variants"("material_id", "sort_order");

-- CreateIndex
CREATE UNIQUE INDEX "material_variants_material_id_variant_name_key" ON "material_variants"("material_id", "variant_name");

-- CreateIndex
CREATE INDEX "inventory_transactions_variant_id_occurred_at_idx" ON "inventory_transactions"("variant_id", "occurred_at");

-- CreateIndex
CREATE INDEX "inventory_transactions_bill_id_idx" ON "inventory_transactions"("bill_id");

-- CreateIndex
CREATE INDEX "inventory_transactions_return_id_idx" ON "inventory_transactions"("return_id");

-- CreateIndex
CREATE INDEX "inventory_transactions_type_occurred_at_idx" ON "inventory_transactions"("type", "occurred_at");

-- CreateIndex
CREATE UNIQUE INDEX "bills_bill_seq_key" ON "bills"("bill_seq");

-- CreateIndex
CREATE UNIQUE INDEX "bills_bill_number_key" ON "bills"("bill_number");

-- CreateIndex
CREATE INDEX "bills_customer_id_taken_at_idx" ON "bills"("customer_id", "taken_at");

-- CreateIndex
CREATE INDEX "bills_status_expected_return_date_idx" ON "bills"("status", "expected_return_date");

-- CreateIndex
CREATE INDEX "bills_settlement_status_idx" ON "bills"("settlement_status");

-- CreateIndex
CREATE INDEX "bills_taken_at_idx" ON "bills"("taken_at");

-- CreateIndex
CREATE INDEX "bills_customer_phone_idx" ON "bills"("customer_phone");

-- CreateIndex
CREATE INDEX "bills_customer_name_trgm_idx" ON "bills" USING GIN ("customer_name" gin_trgm_ops);

-- CreateIndex
CREATE INDEX "bills_site_location_trgm_idx" ON "bills" USING GIN ("site_location" gin_trgm_ops);

-- CreateIndex
CREATE INDEX "bill_items_variant_id_idx" ON "bill_items"("variant_id");

-- CreateIndex
CREATE UNIQUE INDEX "bill_items_bill_id_variant_id_key" ON "bill_items"("bill_id", "variant_id");

-- CreateIndex
CREATE UNIQUE INDEX "bill_items_bill_id_line_no_key" ON "bill_items"("bill_id", "line_no");

-- CreateIndex
CREATE UNIQUE INDEX "returns_idempotency_key_key" ON "returns"("idempotency_key");

-- CreateIndex
CREATE INDEX "returns_bill_id_returned_at_idx" ON "returns"("bill_id", "returned_at");

-- CreateIndex
CREATE INDEX "returns_returned_at_idx" ON "returns"("returned_at");

-- CreateIndex
CREATE UNIQUE INDEX "returns_bill_id_return_no_key" ON "returns"("bill_id", "return_no");

-- CreateIndex
CREATE INDEX "return_items_bill_item_id_idx" ON "return_items"("bill_item_id");

-- CreateIndex
CREATE UNIQUE INDEX "return_items_return_id_bill_item_id_condition_key" ON "return_items"("return_id", "bill_item_id", "condition");

-- CreateIndex
CREATE UNIQUE INDEX "payments_idempotency_key_key" ON "payments"("idempotency_key");

-- CreateIndex
CREATE INDEX "payments_bill_id_created_at_idx" ON "payments"("bill_id", "created_at");

-- CreateIndex
CREATE INDEX "payments_status_type_idx" ON "payments"("status", "type");

-- CreateIndex
CREATE INDEX "payments_received_at_idx" ON "payments"("received_at");

-- CreateIndex
CREATE INDEX "bill_charges_bill_id_idx" ON "bill_charges"("bill_id");

-- CreateIndex
CREATE INDEX "audit_logs_entity_type_entity_id_created_at_idx" ON "audit_logs"("entity_type", "entity_id", "created_at");

-- CreateIndex
CREATE INDEX "audit_logs_action_created_at_idx" ON "audit_logs"("action", "created_at");

-- CreateIndex
CREATE INDEX "audit_logs_created_at_idx" ON "audit_logs"("created_at");

-- AddForeignKey
ALTER TABLE "sessions" ADD CONSTRAINT "sessions_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "accounts" ADD CONSTRAINT "accounts_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "business_profiles" ADD CONSTRAINT "business_profiles_created_by_id_fkey" FOREIGN KEY ("created_by_id") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "customers" ADD CONSTRAINT "customers_created_by_id_fkey" FOREIGN KEY ("created_by_id") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "customers" ADD CONSTRAINT "customers_archived_by_id_fkey" FOREIGN KEY ("archived_by_id") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "customer_documents" ADD CONSTRAINT "customer_documents_customer_id_fkey" FOREIGN KEY ("customer_id") REFERENCES "customers"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "customer_documents" ADD CONSTRAINT "customer_documents_uploaded_by_id_fkey" FOREIGN KEY ("uploaded_by_id") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "material_variants" ADD CONSTRAINT "material_variants_material_id_fkey" FOREIGN KEY ("material_id") REFERENCES "materials"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "inventory" ADD CONSTRAINT "inventory_variant_id_fkey" FOREIGN KEY ("variant_id") REFERENCES "material_variants"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "inventory_transactions" ADD CONSTRAINT "inventory_transactions_variant_id_fkey" FOREIGN KEY ("variant_id") REFERENCES "material_variants"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "inventory_transactions" ADD CONSTRAINT "inventory_transactions_bill_id_fkey" FOREIGN KEY ("bill_id") REFERENCES "bills"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "inventory_transactions" ADD CONSTRAINT "inventory_transactions_bill_item_id_fkey" FOREIGN KEY ("bill_item_id") REFERENCES "bill_items"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "inventory_transactions" ADD CONSTRAINT "inventory_transactions_return_id_fkey" FOREIGN KEY ("return_id") REFERENCES "returns"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "inventory_transactions" ADD CONSTRAINT "inventory_transactions_return_item_id_fkey" FOREIGN KEY ("return_item_id") REFERENCES "return_items"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "inventory_transactions" ADD CONSTRAINT "inventory_transactions_customer_id_fkey" FOREIGN KEY ("customer_id") REFERENCES "customers"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "inventory_transactions" ADD CONSTRAINT "inventory_transactions_created_by_id_fkey" FOREIGN KEY ("created_by_id") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "bills" ADD CONSTRAINT "bills_customer_id_fkey" FOREIGN KEY ("customer_id") REFERENCES "customers"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "bills" ADD CONSTRAINT "bills_business_profile_id_fkey" FOREIGN KEY ("business_profile_id") REFERENCES "business_profiles"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "bills" ADD CONSTRAINT "bills_created_by_id_fkey" FOREIGN KEY ("created_by_id") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "bills" ADD CONSTRAINT "bills_generated_by_id_fkey" FOREIGN KEY ("generated_by_id") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "bills" ADD CONSTRAINT "bills_cancelled_by_id_fkey" FOREIGN KEY ("cancelled_by_id") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "bills" ADD CONSTRAINT "bills_archived_by_id_fkey" FOREIGN KEY ("archived_by_id") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "bill_items" ADD CONSTRAINT "bill_items_bill_id_fkey" FOREIGN KEY ("bill_id") REFERENCES "bills"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "bill_items" ADD CONSTRAINT "bill_items_variant_id_fkey" FOREIGN KEY ("variant_id") REFERENCES "material_variants"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "returns" ADD CONSTRAINT "returns_bill_id_fkey" FOREIGN KEY ("bill_id") REFERENCES "bills"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "returns" ADD CONSTRAINT "returns_processed_by_id_fkey" FOREIGN KEY ("processed_by_id") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "returns" ADD CONSTRAINT "returns_voided_by_id_fkey" FOREIGN KEY ("voided_by_id") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "return_items" ADD CONSTRAINT "return_items_return_id_fkey" FOREIGN KEY ("return_id") REFERENCES "returns"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "return_items" ADD CONSTRAINT "return_items_bill_item_id_fkey" FOREIGN KEY ("bill_item_id") REFERENCES "bill_items"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "payments" ADD CONSTRAINT "payments_bill_id_fkey" FOREIGN KEY ("bill_id") REFERENCES "bills"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "payments" ADD CONSTRAINT "payments_return_id_fkey" FOREIGN KEY ("return_id") REFERENCES "returns"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "payments" ADD CONSTRAINT "payments_recorded_by_id_fkey" FOREIGN KEY ("recorded_by_id") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "payments" ADD CONSTRAINT "payments_status_changed_by_id_fkey" FOREIGN KEY ("status_changed_by_id") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "bill_charges" ADD CONSTRAINT "bill_charges_bill_id_fkey" FOREIGN KEY ("bill_id") REFERENCES "bills"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "bill_charges" ADD CONSTRAINT "bill_charges_return_item_id_fkey" FOREIGN KEY ("return_item_id") REFERENCES "return_items"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "bill_charges" ADD CONSTRAINT "bill_charges_created_by_id_fkey" FOREIGN KEY ("created_by_id") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "bill_charges" ADD CONSTRAINT "bill_charges_voided_by_id_fkey" FOREIGN KEY ("voided_by_id") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "audit_logs" ADD CONSTRAINT "audit_logs_actor_id_fkey" FOREIGN KEY ("actor_id") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE CASCADE;


-- ─── 1. CHECK constraints ───────────────────────────────────────────────────

ALTER TABLE users
  ADD CONSTRAINT users_role_valid CHECK (role IN ('admin', 'staff'));

ALTER TABLE business_profiles
  ADD CONSTRAINT business_profiles_version_positive CHECK (version >= 1),
  ADD CONSTRAINT business_profiles_name_present     CHECK (btrim(name) <> ''),
  ADD CONSTRAINT business_profiles_has_phone        CHECK (cardinality(phones) >= 1);

ALTER TABLE counters
  ADD CONSTRAINT counters_value_nonnegative CHECK (value >= 0);

ALTER TABLE customers
  ADD CONSTRAINT customers_name_present     CHECK (btrim(name) <> ''),
  ADD CONSTRAINT customers_location_present CHECK (btrim(location) <> ''),
  -- stored normalised: +91 98652 76111 / 09865276111 / 9865276111 → 9865276111
  ADD CONSTRAINT customers_phone_normalised CHECK (phone ~ '^[6-9][0-9]{9}$'),
  ADD CONSTRAINT customers_archive_recorded CHECK ((archived_at IS NULL) = (archived_by_id IS NULL));

ALTER TABLE customer_documents
  ADD CONSTRAINT customer_documents_size_positive      CHECK (size_bytes > 0),
  ADD CONSTRAINT customer_documents_id_proof_sensitive CHECK (type <> 'ID_PROOF' OR is_sensitive);

ALTER TABLE materials
  ADD CONSTRAINT materials_name_present CHECK (btrim(name) <> '');

ALTER TABLE material_variants
  -- NULL = not configured yet (no invented prices); such a variant cannot be billed
  ADD CONSTRAINT material_variants_rate_nonnegative      CHECK (rate_per_day IS NULL OR rate_per_day >= 0),
  ADD CONSTRAINT material_variants_threshold_nonnegative CHECK (low_stock_threshold IS NULL OR low_stock_threshold >= 0),
  ADD CONSTRAINT material_variants_name_trimmed          CHECK (variant_name = btrim(variant_name));

-- available = total − rented − held can never go below zero
ALTER TABLE inventory
  ADD CONSTRAINT inventory_total_nonnegative  CHECK (total_quantity >= 0),
  ADD CONSTRAINT inventory_rented_nonnegative CHECK (rented_quantity >= 0),
  ADD CONSTRAINT inventory_held_nonnegative   CHECK (held_quantity >= 0),
  ADD CONSTRAINT inventory_within_stock       CHECK (rented_quantity + held_quantity <= total_quantity);

-- Every movement type has one fixed effect on the counters, and says where it came from.
ALTER TABLE inventory_transactions
  ADD CONSTRAINT inventory_transactions_effect CHECK (
    CASE type
      WHEN 'INITIAL_STOCK'        THEN total_delta > 0  AND rented_delta = 0 AND held_delta = 0
      WHEN 'MANUAL_ADJUSTMENT'    THEN total_delta <> 0 AND rented_delta = 0 AND held_delta = 0
      WHEN 'RENTAL_OUT'           THEN rented_delta > 0 AND total_delta = 0  AND held_delta = 0
      WHEN 'RETURN_IN'            THEN rented_delta < 0 AND total_delta = 0  AND held_delta = 0
      WHEN 'RETURN_TO_HOLD'       THEN rented_delta < 0 AND total_delta = 0  AND held_delta = -rented_delta
      WHEN 'HOLD_RELEASE'         THEN held_delta < 0   AND total_delta = 0  AND rented_delta = 0
      WHEN 'HOLD_WRITE_OFF'       THEN held_delta < 0   AND total_delta = held_delta AND rented_delta = 0
      WHEN 'BILL_VOID_REVERSAL'   THEN rented_delta < 0 AND total_delta = 0  AND held_delta = 0
      WHEN 'RETURN_VOID_REVERSAL' THEN rented_delta > 0 AND total_delta = 0  AND held_delta IN (0, -rented_delta)
      ELSE false
    END),
  ADD CONSTRAINT inventory_transactions_source CHECK (
    CASE
      WHEN type IN ('RENTAL_OUT', 'BILL_VOID_REVERSAL') THEN
        bill_id IS NOT NULL AND bill_item_id IS NOT NULL AND customer_id IS NOT NULL
      WHEN type IN ('RETURN_IN', 'RETURN_TO_HOLD', 'RETURN_VOID_REVERSAL') THEN
        bill_id IS NOT NULL AND bill_item_id IS NOT NULL AND customer_id IS NOT NULL
        AND return_id IS NOT NULL AND return_item_id IS NOT NULL
      ELSE
        btrim(coalesce(reason, '')) <> ''   -- admin movements must say why
    END);

ALTER TABLE bills
  -- SMS-000001 … SMS-999999, then SMS-1000000 (never truncated)
  ADD CONSTRAINT bills_number_matches_seq CHECK (
    bill_seq >= 1
    AND bill_number = 'SMS-' || lpad(bill_seq::text, greatest(6, length(bill_seq::text)), '0')),
  ADD CONSTRAINT bills_expected_days_positive    CHECK (expected_days >= 1),
  ADD CONSTRAINT bills_site_location_present     CHECK (btrim(site_location) <> ''),
  ADD CONSTRAINT bills_customer_name_present     CHECK (btrim(customer_name) <> ''),
  ADD CONSTRAINT bills_customer_phone_normalised CHECK (customer_phone ~ '^[6-9][0-9]{9}$'),
  ADD CONSTRAINT bills_estimate_nonnegative      CHECK (estimated_amount >= 0),
  ADD CONSTRAINT bills_version_positive          CHECK (version >= 1),
  ADD CONSTRAINT bills_draft_advance_nonnegative CHECK (draft_advance_amount IS NULL OR draft_advance_amount >= 0),
  -- wizard payment input exists only while DRAFT; generation turns it into a Payment row
  ADD CONSTRAINT bills_draft_advance_only_in_draft CHECK (
    status = 'DRAFT'
    OR (draft_advance_amount IS NULL AND draft_advance_method IS NULL
        AND draft_advance_received IS NULL AND draft_advance_reference IS NULL)),
  ADD CONSTRAINT bills_generation_recorded CHECK (
    CASE status
      WHEN 'DRAFT'     THEN generated_at IS NULL AND generated_by_id IS NULL
      WHEN 'CANCELLED' THEN (generated_at IS NULL) = (generated_by_id IS NULL)
      ELSE generated_at IS NOT NULL AND generated_by_id IS NOT NULL
    END),
  -- cancelling a draft needs no reason; voiding a generated bill does
  ADD CONSTRAINT bills_cancellation_recorded CHECK (
    (status = 'CANCELLED') = (cancelled_at IS NOT NULL)
    AND (cancelled_at IS NULL) = (cancelled_by_id IS NULL)
    AND (status <> 'CANCELLED' OR generated_at IS NULL OR btrim(coalesce(cancel_reason, '')) <> '')),
  ADD CONSTRAINT bills_archive_rules CHECK (
    (archived_at IS NULL) = (archived_by_id IS NULL)
    AND (archived_at IS NULL OR status IN ('RETURNED', 'CANCELLED'))),
  ADD CONSTRAINT bills_draft_has_no_money CHECK (status <> 'DRAFT' OR settlement_status = 'NO_DUE');

ALTER TABLE bill_items
  ADD CONSTRAINT bill_items_line_no_positive        CHECK (line_no >= 1),
  ADD CONSTRAINT bill_items_quantity_positive       CHECK (quantity >= 1),
  ADD CONSTRAINT bill_items_rate_nonnegative        CHECK (rate_per_day >= 0),
  ADD CONSTRAINT bill_items_estimate_nonnegative    CHECK (estimated_amount >= 0),
  ADD CONSTRAINT bill_items_returns_nonnegative     CHECK (returned_quantity >= 0 AND damaged_quantity >= 0 AND lost_quantity >= 0),
  -- nothing can come back that was not taken
  ADD CONSTRAINT bill_items_returns_within_quantity CHECK (returned_quantity + damaged_quantity + lost_quantity <= quantity);

ALTER TABLE returns
  ADD CONSTRAINT returns_number_positive CHECK (return_no >= 1),
  ADD CONSTRAINT returns_void_recorded CHECK (
    (voided_at IS NULL) = (voided_by_id IS NULL)
    AND (voided_at IS NULL OR btrim(coalesce(void_reason, '')) <> ''));

ALTER TABLE return_items
  ADD CONSTRAINT return_items_quantity_positive CHECK (quantity >= 1),
  ADD CONSTRAINT return_items_days_positive     CHECK (chargeable_days >= 1),
  ADD CONSTRAINT return_items_rate_nonnegative  CHECK (rate_per_day >= 0),
  ADD CONSTRAINT return_items_amount_is_product CHECK (amount = quantity * rate_per_day * chargeable_days),
  ADD CONSTRAINT return_items_note_for_damage_or_loss CHECK (condition = 'GOOD' OR btrim(coalesce(note, '')) <> '');

ALTER TABLE payments
  ADD CONSTRAINT payments_amount_positive CHECK (amount > 0),
  ADD CONSTRAINT payments_method_rules CHECK (
    CASE WHEN type = 'DISCOUNT' THEN method IS NULL AND transaction_reference IS NULL
         ELSE method IS NOT NULL
    END),
  ADD CONSTRAINT payments_reference_only_for_upi CHECK (transaction_reference IS NULL OR method = 'UPI'),
  ADD CONSTRAINT payments_discount_reason        CHECK (type <> 'DISCOUNT' OR btrim(coalesce(note, '')) <> ''),
  -- only money coming in can be "promised"; refunds and discounts are recorded when they happen
  ADD CONSTRAINT payments_pending_only_incoming  CHECK (status <> 'PENDING' OR type IN ('ADVANCE', 'ADDITIONAL')),
  ADD CONSTRAINT payments_received_time          CHECK (status <> 'COMPLETED' OR type = 'DISCOUNT' OR received_at IS NOT NULL),
  ADD CONSTRAINT payments_status_change_recorded CHECK (
    (status_changed_at IS NULL) = (status_changed_by_id IS NULL)
    AND (status <> 'CANCELLED' OR btrim(coalesce(status_change_reason, '')) <> ''));

ALTER TABLE bill_charges
  ADD CONSTRAINT bill_charges_amount_positive     CHECK (amount > 0),
  ADD CONSTRAINT bill_charges_description_present CHECK (btrim(description) <> ''),
  ADD CONSTRAINT bill_charges_void_recorded CHECK (
    (voided_at IS NULL) = (voided_by_id IS NULL)
    AND (voided_at IS NULL OR btrim(coalesce(void_reason, '')) <> ''));

ALTER TABLE audit_logs
  ADD CONSTRAINT audit_logs_action_present CHECK (btrim(action) <> '');


-- ─── 2. Stock ledger → inventory counters ───────────────────────────────────
-- Inserting a movement is the only way to change stock. The trigger applies the
-- movement to the variant's counters; the CHECKs above then refuse anything that
-- would oversell or go negative, which rolls back the whole bill, return or
-- adjustment together with it.

CREATE FUNCTION apply_inventory_transaction() RETURNS trigger
LANGUAGE plpgsql AS $$
BEGIN
  UPDATE inventory
     SET total_quantity  = total_quantity  + NEW.total_delta,
         rented_quantity = rented_quantity + NEW.rented_delta,
         held_quantity   = held_quantity   + NEW.held_delta,
         updated_at      = now()
   WHERE variant_id = NEW.variant_id;
  IF NOT FOUND THEN
    RAISE EXCEPTION 'No inventory row for variant %', NEW.variant_id
      USING ERRCODE = 'foreign_key_violation';
  END IF;
  RETURN NEW;
END;
$$;

CREATE TRIGGER inventory_transactions_apply
  AFTER INSERT ON inventory_transactions
  FOR EACH ROW EXECUTE FUNCTION apply_inventory_transaction();

-- Counters cannot be written directly: rows start at zero, are never deleted,
-- and only the ledger trigger above (running nested, at trigger depth 2) may
-- change them. Nobody can "edit available stock".
CREATE FUNCTION guard_inventory_counters() RETURNS trigger
LANGUAGE plpgsql AS $$
BEGIN
  IF TG_OP = 'INSERT' THEN
    IF NEW.total_quantity <> 0 OR NEW.rented_quantity <> 0 OR NEW.held_quantity <> 0 THEN
      RAISE EXCEPTION 'Inventory starts at zero; record stock with an INITIAL_STOCK movement';
    END IF;
    RETURN NEW;
  ELSIF TG_OP = 'DELETE' THEN
    RAISE EXCEPTION 'Inventory rows are never deleted; deactivate the variant instead';
  END IF;
  IF NEW.variant_id <> OLD.variant_id THEN
    RAISE EXCEPTION 'Inventory rows cannot move to another variant';
  END IF;
  IF pg_trigger_depth() < 2
     AND (NEW.total_quantity, NEW.rented_quantity, NEW.held_quantity)
         IS DISTINCT FROM (OLD.total_quantity, OLD.rented_quantity, OLD.held_quantity) THEN
    RAISE EXCEPTION 'Stock changes only through inventory_transactions';
  END IF;
  RETURN NEW;
END;
$$;

CREATE TRIGGER inventory_guard
  BEFORE INSERT OR UPDATE OR DELETE ON inventory
  FOR EACH ROW EXECUTE FUNCTION guard_inventory_counters();


-- ─── 3. History guards ──────────────────────────────────────────────────────

-- Append-only tables: rows are written once and never changed or removed.
CREATE FUNCTION forbid_update_delete() RETURNS trigger
LANGUAGE plpgsql AS $$
BEGIN
  RAISE EXCEPTION '% is append-only (% refused)', TG_TABLE_NAME, TG_OP;
END;
$$;

CREATE TRIGGER inventory_transactions_append_only BEFORE UPDATE OR DELETE ON inventory_transactions
  FOR EACH ROW EXECUTE FUNCTION forbid_update_delete();
CREATE TRIGGER audit_logs_append_only BEFORE UPDATE OR DELETE ON audit_logs
  FOR EACH ROW EXECUTE FUNCTION forbid_update_delete();
CREATE TRIGGER business_profiles_append_only BEFORE UPDATE OR DELETE ON business_profiles
  FOR EACH ROW EXECUTE FUNCTION forbid_update_delete();
CREATE TRIGGER return_items_append_only BEFORE UPDATE OR DELETE ON return_items
  FOR EACH ROW EXECUTE FUNCTION forbid_update_delete();

-- Bill numbers only move forward and are never reused.
CREATE FUNCTION guard_counters() RETURNS trigger
LANGUAGE plpgsql AS $$
BEGIN
  IF TG_OP = 'DELETE' THEN
    RAISE EXCEPTION 'Counters are never deleted';
  END IF;
  IF NEW.key <> OLD.key OR NEW.value < OLD.value THEN
    RAISE EXCEPTION 'Counter % can only move forward', OLD.key;
  END IF;
  RETURN NEW;
END;
$$;

CREATE TRIGGER counters_guard BEFORE UPDATE OR DELETE ON counters
  FOR EACH ROW EXECUTE FUNCTION guard_counters();

-- Bills are never deleted. The number never changes. Once generated, the
-- customer, taking date/time and every snapshot are frozen; only site
-- location, notes, expected duration, status, settlement and the cancel/archive
-- fields can still change. Cancellation is final.
CREATE FUNCTION guard_bills() RETURNS trigger
LANGUAGE plpgsql AS $$
BEGIN
  IF TG_OP = 'DELETE' THEN
    RAISE EXCEPTION 'Bills are never deleted; cancel, void or archive instead';
  END IF;
  IF (NEW.id, NEW.bill_seq, NEW.bill_number, NEW.created_by_id, NEW.created_at)
     IS DISTINCT FROM (OLD.id, OLD.bill_seq, OLD.bill_number, OLD.created_by_id, OLD.created_at) THEN
    RAISE EXCEPTION 'Bill number % can never change', OLD.bill_number;
  END IF;
  IF OLD.status = 'CANCELLED' AND NEW.status <> 'CANCELLED' THEN
    RAISE EXCEPTION 'Bill % is cancelled; cancellation is final', OLD.bill_number;
  END IF;
  IF OLD.status <> 'DRAFT' THEN
    IF NEW.status = 'DRAFT' THEN
      RAISE EXCEPTION 'Bill % has been generated and cannot go back to draft', OLD.bill_number;
    END IF;
    IF (NEW.customer_id, NEW.taken_at, NEW.customer_name, NEW.customer_phone, NEW.customer_location,
        NEW.business_profile_id, NEW.day_count_rule, NEW.time_zone, NEW.paper_bill_number,
        NEW.generated_at, NEW.generated_by_id)
       IS DISTINCT FROM
       (OLD.customer_id, OLD.taken_at, OLD.customer_name, OLD.customer_phone, OLD.customer_location,
        OLD.business_profile_id, OLD.day_count_rule, OLD.time_zone, OLD.paper_bill_number,
        OLD.generated_at, OLD.generated_by_id) THEN
      RAISE EXCEPTION 'Bill % has been generated; its customer, taking date and snapshots are locked',
        OLD.bill_number;
    END IF;
  END IF;
  RETURN NEW;
END;
$$;

CREATE TRIGGER bills_guard BEFORE UPDATE OR DELETE ON bills
  FOR EACH ROW EXECUTE FUNCTION guard_bills();

-- Lines can be added, changed or removed only while the bill is a draft. After
-- generation only the running return totals (and the estimate, when an admin
-- changes the expected duration) may change.
CREATE FUNCTION guard_bill_items() RETURNS trigger
LANGUAGE plpgsql AS $$
DECLARE
  bill_state rental_status;
BEGIN
  SELECT status INTO bill_state FROM bills WHERE id = COALESCE(NEW.bill_id, OLD.bill_id);

  IF TG_OP = 'INSERT' THEN
    IF bill_state <> 'DRAFT' THEN
      RAISE EXCEPTION 'Lines can only be added while the bill is a draft';
    END IF;
    IF NEW.returned_quantity <> 0 OR NEW.damaged_quantity <> 0 OR NEW.lost_quantity <> 0 THEN
      RAISE EXCEPTION 'A new line cannot already have returns';
    END IF;
    RETURN NEW;
  ELSIF TG_OP = 'DELETE' THEN
    IF bill_state <> 'DRAFT' THEN
      RAISE EXCEPTION 'Lines of a generated bill cannot be removed';
    END IF;
    RETURN OLD;
  END IF;

  IF NEW.bill_id <> OLD.bill_id THEN
    RAISE EXCEPTION 'A line cannot move to another bill';
  END IF;
  IF bill_state = 'DRAFT' THEN
    IF NEW.returned_quantity <> 0 OR NEW.damaged_quantity <> 0 OR NEW.lost_quantity <> 0 THEN
      RAISE EXCEPTION 'A draft cannot have returns';
    END IF;
  ELSIF (NEW.line_no, NEW.variant_id, NEW.material_name, NEW.variant_name, NEW.quantity, NEW.rate_per_day)
        IS DISTINCT FROM
        (OLD.line_no, OLD.variant_id, OLD.material_name, OLD.variant_name, OLD.quantity, OLD.rate_per_day) THEN
    RAISE EXCEPTION 'Material lines, quantities and rates are locked once the bill is generated';
  END IF;
  RETURN NEW;
END;
$$;

CREATE TRIGGER bill_items_guard BEFORE INSERT OR UPDATE OR DELETE ON bill_items
  FOR EACH ROW EXECUTE FUNCTION guard_bill_items();

-- A processed return is never edited or deleted. It can be voided once (admin,
-- with reason); the service reverses its stock movements in the same transaction.
CREATE FUNCTION guard_returns() RETURNS trigger
LANGUAGE plpgsql AS $$
BEGIN
  IF TG_OP = 'DELETE' THEN
    RAISE EXCEPTION 'Returns are never deleted; void the return instead';
  END IF;
  IF OLD.voided_at IS NOT NULL THEN
    RAISE EXCEPTION 'Return % is already voided', OLD.return_no;
  END IF;
  IF (NEW.id, NEW.bill_id, NEW.return_no, NEW.returned_at, NEW.notes, NEW.idempotency_key,
      NEW.processed_by_id, NEW.created_at)
     IS DISTINCT FROM
     (OLD.id, OLD.bill_id, OLD.return_no, OLD.returned_at, OLD.notes, OLD.idempotency_key,
      OLD.processed_by_id, OLD.created_at) THEN
    RAISE EXCEPTION 'A processed return cannot be edited; void it and record it again';
  END IF;
  RETURN NEW;
END;
$$;

CREATE TRIGGER returns_guard BEFORE UPDATE OR DELETE ON returns
  FOR EACH ROW EXECUTE FUNCTION guard_returns();

-- Payments are never deleted, and their bill, type, amount and note never change.
-- Only the status moves: PENDING → COMPLETED | CANCELLED, COMPLETED → CANCELLED.
-- Method, reference and received time can be filled in only when a promised
-- payment is actually received.
CREATE FUNCTION guard_payments() RETURNS trigger
LANGUAGE plpgsql AS $$
BEGIN
  IF TG_OP = 'DELETE' THEN
    RAISE EXCEPTION 'Payments are never deleted; cancel them with a reason';
  END IF;
  IF (NEW.id, NEW.bill_id, NEW.type, NEW.amount, NEW.note, NEW.return_id, NEW.idempotency_key,
      NEW.recorded_by_id, NEW.created_at)
     IS DISTINCT FROM
     (OLD.id, OLD.bill_id, OLD.type, OLD.amount, OLD.note, OLD.return_id, OLD.idempotency_key,
      OLD.recorded_by_id, OLD.created_at) THEN
    RAISE EXCEPTION 'A payment''s bill, type and amount never change; cancel it and record a new one';
  END IF;
  IF NEW.status = OLD.status THEN
    IF (NEW.method, NEW.transaction_reference, NEW.received_at,
        NEW.status_changed_at, NEW.status_changed_by_id, NEW.status_change_reason)
       IS DISTINCT FROM
       (OLD.method, OLD.transaction_reference, OLD.received_at,
        OLD.status_changed_at, OLD.status_changed_by_id, OLD.status_change_reason) THEN
      RAISE EXCEPTION 'Payment details change only together with a status change';
    END IF;
    RETURN NEW;
  END IF;
  IF NOT ((OLD.status = 'PENDING' AND NEW.status IN ('COMPLETED', 'CANCELLED'))
       OR (OLD.status = 'COMPLETED' AND NEW.status = 'CANCELLED')) THEN
    RAISE EXCEPTION 'Payment status cannot change from % to %', OLD.status, NEW.status;
  END IF;
  IF NOT (OLD.status = 'PENDING' AND NEW.status = 'COMPLETED')
     AND (NEW.method, NEW.transaction_reference, NEW.received_at)
         IS DISTINCT FROM (OLD.method, OLD.transaction_reference, OLD.received_at) THEN
    RAISE EXCEPTION 'Method and reference can only be set when a pending payment is received';
  END IF;
  RETURN NEW;
END;
$$;

CREATE TRIGGER payments_guard BEFORE UPDATE OR DELETE ON payments
  FOR EACH ROW EXECUTE FUNCTION guard_payments();


-- ─── 4. Read-only views ─────────────────────────────────────────────────────

-- Money on each bill, always calculated from the ledgers — never a stored total.
-- balance > 0: the customer owes that much · balance < 0: refund due.
-- While materials are still out, rental_charges covers only the batches
-- returned so far; the balance is final once the bill is RETURNED or voided.
CREATE VIEW bill_financials AS
SELECT b.id          AS bill_id,
       b.bill_number,
       b.status,
       coalesce(rc.rental_charges, 0) AS rental_charges,
       coalesce(ec.extra_charges, 0)  AS extra_charges,
       coalesce(p.received, 0)        AS received,
       coalesce(p.refunded, 0)        AS refunded,
       coalesce(p.discounts, 0)       AS discounts,
       coalesce(p.pending, 0)         AS pending,
       coalesce(rc.rental_charges, 0) + coalesce(ec.extra_charges, 0) - coalesce(p.discounts, 0)
         - (coalesce(p.received, 0) - coalesce(p.refunded, 0)) AS balance
FROM bills b
LEFT JOIN LATERAL (
  SELECT sum(ri.amount) AS rental_charges
  FROM returns r
  JOIN return_items ri ON ri.return_id = r.id
  WHERE r.bill_id = b.id AND r.voided_at IS NULL
) rc ON true
LEFT JOIN LATERAL (
  SELECT sum(c.amount) AS extra_charges
  FROM bill_charges c
  WHERE c.bill_id = b.id AND c.voided_at IS NULL
) ec ON true
LEFT JOIN LATERAL (
  SELECT sum(amount) FILTER (WHERE status = 'COMPLETED' AND type IN ('ADVANCE', 'ADDITIONAL')) AS received,
         sum(amount) FILTER (WHERE status = 'COMPLETED' AND type = 'REFUND')                  AS refunded,
         sum(amount) FILTER (WHERE status = 'COMPLETED' AND type = 'DISCOUNT')                AS discounts,
         sum(amount) FILTER (WHERE status = 'PENDING')                                        AS pending
  FROM payments
  WHERE bill_id = b.id
) p ON true;

-- Integrity checks, run by a scheduled job and by the test suite. Each view
-- must always be empty; any row means data drifted from its ledger.

-- Stock counters vs. the stock ledger.
CREATE VIEW inventory_discrepancies AS
SELECT i.variant_id,
       i.total_quantity,  coalesce(l.total, 0)  AS ledger_total,
       i.rented_quantity, coalesce(l.rented, 0) AS ledger_rented,
       i.held_quantity,   coalesce(l.held, 0)   AS ledger_held
FROM inventory i
LEFT JOIN (
  SELECT variant_id,
         sum(total_delta)  AS total,
         sum(rented_delta) AS rented,
         sum(held_delta)   AS held
  FROM inventory_transactions
  GROUP BY variant_id
) l ON l.variant_id = i.variant_id
WHERE (i.total_quantity, i.rented_quantity, i.held_quantity)
      IS DISTINCT FROM (coalesce(l.total, 0), coalesce(l.rented, 0), coalesce(l.held, 0));

-- Pieces "currently rented" vs. pieces still pending on open bills.
CREATE VIEW rented_stock_discrepancies AS
SELECT i.variant_id,
       i.rented_quantity,
       coalesce(o.pending, 0) AS pending_on_bills
FROM inventory i
LEFT JOIN (
  SELECT bi.variant_id,
         sum(bi.quantity - bi.returned_quantity - bi.damaged_quantity - bi.lost_quantity) AS pending
  FROM bill_items bi
  JOIN bills b ON b.id = bi.bill_id
  WHERE b.status IN ('ACTIVE', 'PARTIALLY_RETURNED', 'RETURNED')
  GROUP BY bi.variant_id
) o ON o.variant_id = i.variant_id
WHERE i.rented_quantity <> coalesce(o.pending, 0);

-- Each bill line's return totals vs. its (non-voided) return batches.
CREATE VIEW bill_item_return_discrepancies AS
SELECT bi.id AS bill_item_id,
       bi.bill_id,
       bi.returned_quantity, coalesce(x.good, 0)    AS batches_good,
       bi.damaged_quantity,  coalesce(x.damaged, 0) AS batches_damaged,
       bi.lost_quantity,     coalesce(x.lost, 0)    AS batches_lost
FROM bill_items bi
LEFT JOIN (
  SELECT ri.bill_item_id,
         sum(ri.quantity) FILTER (WHERE ri.condition = 'GOOD')    AS good,
         sum(ri.quantity) FILTER (WHERE ri.condition = 'DAMAGED') AS damaged,
         sum(ri.quantity) FILTER (WHERE ri.condition = 'LOST')    AS lost
  FROM return_items ri
  JOIN returns r ON r.id = ri.return_id AND r.voided_at IS NULL
  GROUP BY ri.bill_item_id
) x ON x.bill_item_id = bi.id
WHERE (bi.returned_quantity, bi.damaged_quantity, bi.lost_quantity)
      IS DISTINCT FROM (coalesce(x.good, 0), coalesce(x.damaged, 0), coalesce(x.lost, 0));
